### ISSUE TITLE
Como professor, eu gostaria de atualizar a informação de um aluno ou removê-lo

### ISSUE THREAD

**Issue by thassis** [thassis/gestao-escolar#3]
- [x] criar API de edição e deleção do aluno [Misael]
- [ ] criar telas de editar aluno [Daniel]
- [ ] integrar as telas com o backend [Daniel]

**Comment by misaelrezende** [comment]
- [x] Verificar que a busca de um aluno funciona
- [x] Verificar que um aluno é atualizado
- [x] Verificar que um aluno é deletado
- [x] Garantir que a API do frontend e do backend funcionem para buscar um aluno
